### ISSUE TITLE
Error instalando vagrant (SOLUCIÓN)

### ISSUE THREAD

**Issue by alejandrososa** [diegoseso/phpunit-course#1]
Buenas mi gente, después de instalar vagrant en mi mac y actualizar mi repo del fork que hice saltaron 2 errores de directorio y de puerto.

```
Sosa-Johnson:maquinavirtual grace$ vagrant up
Bringing machine 'developer' up with 'virtualbox' provider...
==> developer: Box 'puphpet/ubuntu1604-x64' could not be found. Attempting to find and install...
    developer: Box Provider: virtualbox
    developer: Box Version: >= 0
==> developer: Loading metadata for box 'puphpet/ubuntu1604-x64'
    developer: URL: https://atlas.hashicorp.com/puphpet/ubuntu1604-x64
==> developer: Adding box 'puphpet/ubuntu1604-x64' (v20161004) for provider: virtualbox
    developer: Downloading: https://atlas.hashicorp.com/puphpet/boxes/ubuntu1604-x64/versions/20161004/providers/virtualbox.box
==> developer: Successfully added box 'puphpet/ubuntu1604-x64' (v20161004) for 'virtualbox'!
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The host path of the shared folder is missing: /apps/html
* Forwarded port '2222' (host port) is declared multiple times with the protocol 'tcp'.
```

Pare resolverlo edite la configuración que se encuentra en 
**/DIRECTORIO-DESCOMPRIMIDO/puphpet/config.yaml** 

**Primer error** 
Se resuelve creando el directorio en raíz /apps/html o en mi caso, como ya tengo un directorio para los desarrollos que realizo, edito la sección synced_folder el source que es lo que enlaza la carpeta compartida entre la maquina virtual y tu directorio en la linea 45:

```
synced_folder:
            vflsf_7bshmwqnyfpm:
                source: /Users/grace/Sites
                target: /var/www
                sync_type: default
```

**Segundo error**
Se resuelve cambiando el puerto 2222 a 2223 en la linea 27

```
forwarded_port:
            vflmnfp_vruy1gm6a526:
                id: "ssh"
                host: '2223'
                guest: '22'
```

De momento sigo con la instalación.
Saludos a todos.

**Comment by diegoseso** [comment]
Corregido con commit [ 1112a0 ](https://github.com/diegoseso/phpunit-course/commit/8a4172c57b0e6da3f5ee9ca1b2dbf0d12d1112a0)
@alejandrososa tiene razón, por defecto he configurado la máquina para tener un forwarded port ssh en el 2222 pero este no puede ser usado, he modificado el fichero de configuración .yaml de modo que ahora se asuma el puerto 2223, en cuando al folder compartido me ha parecido propicio mantener el folder /apps/html pero si su entorno host es windows o no desea utilizar este folder puede hacer exactamente lo que se explica anteriormente.
